### ISSUE TITLE
Add a readme

### ISSUE THREAD

**Issue by wooorm** [syntax-tree/mdastscript#1]
Hey! 👋

Been a while! I saw this project again and was wondering whether I can do anything to help?

**Comment by kt3k** [comment]
I actually don't have idea about what mdastscript is. (I guess it's something like hyperscript for markdown but not sure about its interface or public apis.)

I started helping this project just because I proposed we should have constants (like `const ROOT = 'root'`) exposed in some way in the registry. So what I've done so far is just setting up the repository and having put node constants (ROOT, PARAGRAPH, BLOCKQUOTE etc).

So if possible, can you describe the usage of mdastscript with some examples?

**Comment by wooorm** [comment]
Sorry, I never got around to this! Thanks for your initial work. There’s now https://github.com/mike-north/mdast-builder and I think that does exactly what’s needed, so I’ll archive this project in favour of that one!
